kind: Deployment
apiVersion: apps/v1
metadata:
  name: edureka-project
  labels:
    app: xyztechnologies
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: xyztechnologies
  template:
    metadata:
      labels:
        app: xyztechnologies
    spec:
      containers:
      - name: xyztechnologiesjavaapp
        image: buntatiba/xyztechnologies:bno
        ports:
        - name: http
          containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: edureka-project-svc
spec:
  type: NodePort
  selector:
    app: xyztechnologies
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001